"""empty message

Revision ID: 129ad31e81c4
Revises: 3b91e9907e2a
Create Date: 2021-04-22 16:11:06.367912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129ad31e81c4'
down_revision = '3b91e9907e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('numberToken', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['numberToken'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'numberToken')
    # ### end Alembic commands ###
