"""empty message

Revision ID: 3b91e9907e2a
Revises: d987cfc84166
Create Date: 2021-04-09 21:49:34.327779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b91e9907e2a'
down_revision = 'd987cfc84166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recinto', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('recinto', sa.Column('phone', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'recinto', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recinto', type_='unique')
    op.drop_column('recinto', 'phone')
    op.drop_column('recinto', 'email')
    # ### end Alembic commands ###
