"""empty message

Revision ID: 444ad7990737
Revises: 73898954e65c
Create Date: 2021-04-08 01:16:35.610819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444ad7990737'
down_revision = '73898954e65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=80), nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
