"""empty message

Revision ID: 73898954e65c
Revises: 412192296a35
Create Date: 2021-04-07 17:35:14.144756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73898954e65c'
down_revision = '412192296a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
