"""empty message

Revision ID: 7b476eb2ed5b
Revises: f0e1456dccc7
Create Date: 2021-04-09 17:42:28.278686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b476eb2ed5b'
down_revision = 'f0e1456dccc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recinto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRecinto', sa.String(length=80), nullable=False),
    sa.Column('openHour', sa.Integer(), nullable=False),
    sa.Column('closeHour', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nameRecinto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recinto')
    # ### end Alembic commands ###
