"""empty message

Revision ID: b5a70564a25c
Revises: 3b91e9907e2a
Create Date: 2021-04-10 07:06:44.658145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a70564a25c'
down_revision = '3b91e9907e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('fecha', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'fecha')
    # ### end Alembic commands ###
