"""empty message

Revision ID: d4fd38253c5c
Revises: 444ad7990737
Create Date: 2021-04-08 01:29:12.883088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fd38253c5c'
down_revision = '444ad7990737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fisrtName', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('lastName', sa.String(length=80), nullable=False))
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('lastname', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'fisrtName')
    # ### end Alembic commands ###
