"""empty message

Revision ID: f0e1456dccc7
Revises: d4fd38253c5c
Create Date: 2021-04-08 02:17:12.133649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e1456dccc7'
down_revision = 'd4fd38253c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstName', sa.String(length=80), nullable=False))
    op.drop_column('user', 'fisrtName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fisrtName', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('user', 'firstName')
    # ### end Alembic commands ###
